[FEATURE] : [경매 종료가 임박한 진행중인 경매 목록 조회]
TaskSprints/auction pull request #37
Opened 2024-09-05 08:58 UTC by na0th

1. 경매 종료가 임박한 진행중인 경매 목록 조회 추가

미흡 : 성능 개선 못함,
/auction으로 엔드포인트 합쳐야 하는데 못했음,
테스트쪽 리뷰 받아야 함.

---
name: Pull Request
about: '풀 리퀘스트를 제출합니다.'
title: "[FEATURE] - [기능명] 또는 [FIX] - [버그 설명]"
labels: ''
assignees: ''

---
https://github.com/TaskSprints/auction/issues/9 에 대한 Issue 을 중점으로 구현
## 🆕 기능 추가 / 🔧 버그 수정

경매 종료가 임박했고, 진행 중인 경매 목록을 조회합니다.

## 📋 변경 사항

## 🔍 테스트 사항
Controller 테스트 미구현

Repository, Service 테스트 미흡, 꼼꼼한 리뷰 필수 

## 📄 관련 문서
- 변경 사항과 관련된 문서나 링크가 있다면 여기에 추가해주세요.

## 📝 추가 사항
- PR과 관련된 다른 중요한 정보나 주의 사항을 기입합니다.

2024-09-05 09:00 UTC, na0th commented on src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
> -
줄맞춤 때문에 TAP 키 한 번 쳣습니다.

2024-09-05 09:01 UTC, na0th commented on src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
> +    }
엔드포인트 /auction으로 합쳐야 했는데, 잘 모르겠어서 분리했습니다. (리팩토링 요청)

2024-09-05 09:04 UTC, na0th commented on src/test/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImplTest.java
> +        }
endTime을 직접 설정해야 해서, 기존 생성자 코드를 그대로 두고, 아래에 파라미터만 1개 늘어난 생성자를 추가했습니다.

2024-09-05 09:20 UTC, polyglot-k requested changes
일단 전체적으로 작업 진행해주셔서 감사합니다! 일단 현재 Service 내부 로직은 의도에 맞게 잘 설계된 것 같습니다.

아쉬운 부분은 CriteriaRepository 는 전체 조회에서의 모든 filter 를 포함할 수 있도록 하려고 구성해 놓은 것이라서, 이를 좀 더 활용했으면 좋았을 것 같습니다.

인자를 추가하는 형태로 진행했어도 괜찮았을 것 같습니다.

Controller 를 새롭게 추가하는 것은, 지금 고민해봤을 때, 마감임박 요소만을 빠르게 불러오는 것을 만들어야하는지에 대한 고민을 가지고 있습니다. 일단 만들게 되었을 때는, 해당 기능을 통해서 `fit`하게 가지고 올 수 있다는 장점이 있는데, 단점은 restful 하지 못할 수도 있다라는 점이 있긴 합니다. 그래서 해당 부분에 대한 유지보수가 조금 필요해 보입니다!

2024-09-06 18:29 UTC, yachimiya reviewed
자주 참여하지 못해서 죄송합니다 :cry: 

수고하셨습니다 :+1:

2024-09-06 18:29 UTC, yachimiya commented on src/main/java/com/tasksprints/auction/api/auction/AuctionController.java
> -
자주 참여하지 못해서 죄송합니다 :cry: 

이런 부분은 리뷰어가 좀 더 핵심적인 부분에 집중할 수 있도록 checkstyle 같은 정적 분석 툴로 검사하거나 CI 파이프라인에서 걸러낼 수 있으면 좋을 것 같네요! :thinking:

2024-09-06 18:29 UTC, yachimiya commented on src/main/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
`LocalDateTime.now()`가 환경에 따라서 깨지기 쉬운 메서드인 것 같아서(예: 배포 환경의 TZ에 따라서 예상하지 못한 결과를 얻을 수 있는 등) 이 부분은 주의가 필요할 것 같네요! :thinking: 

- https://code-run.tistory.com/m/82

2024-09-06 18:29 UTC, yachimiya commented on src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
> +        Auction auction5 = createAuction(seller, LocalDateTime.now().plusHours(20), AuctionCategory.PUBLIC_PAID, AuctionStatus.PENDING);
이런 부분은 테스트에 사용되는 데이터를 빠르게 셋업할 수 있도록 별도의 테스트 픽스처가 있으면 좋을 것 같네요. 오브젝트 마더나 테스트 빌더 등을 통해서 테스트에 사용되는 합리적인 기본값을 설정해두고, 테스트의 대상이 되는 데이터만 외부로 노출시키는 것도 괜찮을 것 같습니다 :thinking:

2024-09-06 18:29 UTC, yachimiya commented on src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
> +            }
이런 부분은 테스트 실패 시 빠르고 정확한 피드백을 받을 수 있도록 `assertAll`이나 `assertSoftly` 같이 soft assertion을 이용하면 괜찮겠다 생각이 들었습니다 :smile:

2024-09-06 18:29 UTC, yachimiya commented on src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
> +        LocalDateTime next24Hours = LocalDateTime.now().plusHours(24);
이 부분 자체는 문제가 없을 수 있지만 테스트 데이터가 동적인 것보다는 고정적이면 외부 환경이나 미묘한 타이밍으로 인한 문제를 약간이나마 배제할 수 있다는 점이 있을 것 같네요 :thinking: 

- https://jojoldu.tistory.com/416

2024-09-07 01:43 UTC, na0th commented on src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
> +        LocalDateTime next24Hours = LocalDateTime.now().plusHours(24);
꼼꼼한 리뷰 감사합니다!! 많이 미숙하지만 지적해주신 부분 검색해서 보완하겠습니다~

2024-09-07 15:17 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
해당 부분은 문서화하여 공유하면 좋을 것 같습니다

2024-09-08 14:53 UTC, KNU-K requested changes

2024-09-08 14:53 UTC, KNU-K commented on src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
> +        Auction auction5 = createAuction(fixedNow.plusHours(20), AuctionStatus.PENDING);
애초에 리스트로 만들면 더 직관적일 것 같아요

2024-09-08 14:53 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepositoryImpl.java
> +                .orderBy(auction.endTime.asc())
`order by`가 성능 저하의 병목지점이 될 수 있음에 유의 해야합니다! 이에 대한 방안을 고려해보고, 최선책으로 `order by`를 사용해야하는 근거를 가지고 오시면 좋을 것 같습니다.!

2024-09-08 14:53 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepositoryImpl.java
> +                .orderBy(auction.endTime.asc())
+ 제가 이전에 만든 filter 함수에 합치는게 더 낫지않을까요? 충분히 합칠 수 있다고 생각이 됩니다.

2024-09-08 14:53 UTC, KNU-K commented on src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
> +        );
LocalDateTime 피드백에 따라 고정으로 변경해주세요

2024-09-08 14:53 UTC, KNU-K commented on src/test/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImplTest.java
> +            .startTime(LocalDateTime.now())
여기도 고정으로 변경해주세요

2024-09-08 14:54 UTC, na0th commented on src/test/java/com/tasksprints/auction/domain/auction/service/AuctionServiceImplTest.java
> +            .startTime(LocalDateTime.now())
넵, 고정으로 변경하겠습니다

2024-09-08 14:55 UTC, na0th commented on src/test/java/com/tasksprints/auction/domain/auction/repository/AuctionRepositoryTest.java
> +        );
넵,

2024-09-08 14:56 UTC, na0th commented on src/main/java/com/tasksprints/auction/domain/auction/repository/support/AuctionCriteriaRepositoryImpl.java
> +                .orderBy(auction.endTime.asc())
넵 노력하겠습니다

2024-09-10 08:18 UTC, merged