[FEATURE] : [Bid uuid 추가 및 uuid를 이용한 조회 기능]
TaskSprints/auction pull request #41
Opened 2024-09-09 14:51 UTC by world-dv

---
name: Pull Request
about: '풀 리퀘스트를 제출합니다.'
title: "[FEATURE] - [기능명] 또는 [FIX] - [버그 설명]"
labels: ''
assignees: ''

---

## 🆕 기능 추가 / 🔧 버그 수정
- **기능 추가**: uuid를 이용해 bid를 조회

## 📋 변경 사항
- Bid.java : uuid 엔티티 추가, Bid 생성 시 uuid 생성 
- BidController.java : get bid controller 생성 
- BidResponse.java : uuid 추가
- BidService.java : get bid by uuid 추가 및 구현
- BidServicelmpl.java : get bid by uuid 추가 및 구현
- BidRepository.java : get bid by uuid 쿼리 추가

## 🔍 테스트 사항
- /api/v1/bid/{uuid}로 조회 시 bid 정보 조회

## 📄 관련 문서

## 📝 추가 사항

2024-09-10 14:34 UTC, KNU-K requested changes
살짝 확인해봤는데 간단하게 보이는 부분에 대해서 리뷰 남겨봤어요

2024-09-10 14:34 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/domain/bid/model/Bid.java
> +    private String uuid;
uuid 를 `unique` 로 설정하고, 중복된 형태가 들어오게 되는 것에 대해서 적은 확률이지만 가능성이 있어서 retry 로직을 넣거나 다른 대체 로직에 대한 부분 있으면 좋을 듯한데 이슈 추가 해도 될까요??

2024-09-10 14:34 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/domain/user/model/User.java
> +    private String nickName; //unique 특성 추가 필요
중복 닉네임 불허하는 목적이라면, `nickName`이 `unique` 옵션을 가지는게 맞는 것 같습니다!

닉네임이 겹쳐도 된다고 조금 착각을 했던 것 같습니다.

2024-09-10 16:08 UTC, yachimiya commented on src/main/java/com/tasksprints/auction/domain/bid/model/Bid.java
> +    }
이런 역할을 잘 할 수 있는 곳이 생성자라고 생각이 되는데, 생성자로 이 생성 로직을 옮겨보는 건 어떤가요? 정적 팩토리 메서드를 통해서 만들거나 아니면 생성자로 통일하는 것도 괜찮은 것 같습니다 :thinking:

2024-09-11 07:34 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/domain/bid/model/Bid.java
> +    }
기존의 정적 팩토리 메소드를 활용하고, 생성자를 통한 `인스턴스`가 만들어지는 것을 방지하기 위해 생성자의 ``AccessLevel`을 제한해도 괜찮을 것 같습니다.  

다른 Entity 에서도 정적 팩토리 메소드 패턴을 활용하고 있는데, 이를 통일하는 형태로 하는건 어떤가 생각이  듭니다.!

@yachimiya

2024-09-11 07:44 UTC, yachimiya commented on src/main/java/com/tasksprints/auction/domain/bid/model/Bid.java
> +    }
괜찮은 것 같습니다! 현재 객체의 생성 방법이 생성자, 빌더, 정적 팩토리 메서드가 있는데 하나로 통일해보면 괜찮겠다는 생각이 들었습니다 :smile:

사실 이 경우에 제가 기획에 참여를 못해서 그런 것일지도 모르는데, 객체 생성을 제어해야 하거나(예: 캐싱, 지연 로딩 등), 입력으로 들어오는 매개변수에 따라 유연하게 하위 타입 객체를 반환하거나, 객체의 생성 패턴이 여러 개일 수 있는 경우 등이 아니면 생성자로도 괜찮지 않을까? 라는 생각이 문득 들었습니다 :thinking:

2024-09-11 09:23 UTC, yachimiya commented on src/main/java/com/tasksprints/auction/domain/bid/model/Bid.java
> +    }
확실하게 확장을 염두해두시고 계시다면 괜찮은 것 같습니다! 만약에 그게 아닌 경우에는 빌더를 통해서 이미 유연하게 객체를 만들 수 있는 방법을 제공하고 있고, 객체의 불변식을 유지하기 위해서 생성자와 정적 팩토리 메서드 두 부분으로 유지 보수 포인트가 늘어나기 때문에 클라이언트에게 불필요한 객체 생성 인터페이스를 노출해서 혼란을 줄 수도 있지 않을까 하는 우려였습니다! :smile:

2024-09-11 09:25 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/domain/bid/model/Bid.java
> +    }
맞습니다! 확실히 복잡성이 올라가긴 해서, 저는 무조건적인 통일이 좋다는 착각을 했었네요.. 하하

이 부분은 추가 확장됨에 따라서 고려해야할 사항으로 이슈 생성해 두겠습니다

2024-09-11 12:50 UTC, world-dv commented on src/main/java/com/tasksprints/auction/domain/bid/model/Bid.java
> +    private String uuid;
넵 ! 이슈 추가해도 좋을 것 같습니다!

2024-09-11 12:51 UTC, world-dv commented on src/main/java/com/tasksprints/auction/common/config/JpaAuditingConfig.java
> +//@EnableJpaAuditing 제거 -> 프로젝트 선언부에 이미 선언되어 있음
제가 실행했을 경우에는 해당 어노테이션이 제거되었을 경우에만 정상 실행되던데, 이 경우는 혹시 다른 해결 방법이 있을 까요?

2024-09-12 00:13 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/common/config/JpaAuditingConfig.java
> +//@EnableJpaAuditing 제거 -> 프로젝트 선언부에 이미 선언되어 있음
테스트 실행 정상적으로 완료되었나요?

2024-09-12 01:28 UTC, world-dv commented on src/main/java/com/tasksprints/auction/common/config/JpaAuditingConfig.java
> +//@EnableJpaAuditing 제거 -> 프로젝트 선언부에 이미 선언되어 있음
테스트 실행이 아닌 프로젝트 실행에서 해당 부분이 오류로 나타났었습니다..

2024-09-12 03:49 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/common/config/JpaAuditingConfig.java
> +//@EnableJpaAuditing 제거 -> 프로젝트 선언부에 이미 선언되어 있음
@world-dv  한번 확인해보겠습니다

2024-10-16 06:09 UTC, CreatorDodo commented
👏👏👏

2024-12-18 11:21 UTC, closed without merging