[FEATURE] : [JWT 토큰 생성 및 검증]
TaskSprints/auction pull request #61
Opened 2024-10-13 05:46 UTC by isyoudwn

## 🆕 기능 추가 / 🔧 버그 수정
- **기능 추가**: JWT 토큰 refresh token과 access token 생성 및 검증 기능 추가

## 📋 변경 사항
- JwtProvider : 토큰을 생성 및 검증
- JwtUtil : Jwt관련 util 성질을 가지고 있는 메소드를 모은 클래스
- JwtProperties : jwt 설정파일에 접근
- JwtResponse : access token과 refresh token을 반환
- User 도메인에 UserRole 클래스 추가

## 🔍 테스트 사항
- JwtProvider 테스트 

## 📝 추가 사항
- JwtUtil 클래스는 리팩토링 예정입니다.

2024-10-14 22:44 UTC, KNU-K requested changes

2024-10-14 22:44 UTC, KNU-K commented on src/main/java/com/tasksprints/auction/common/jwt/JwtProvider.java
> +        Date now = new Date(System.currentTimeMillis());
Date TZ 고정화 부분 수정 필요할거 같아요~ 아까 말한느낌으로 해당 PR 브랜치에 push 해주세요

2024-10-16 06:08 UTC, CreatorDodo commented
👏👏👏

2024-10-24 08:34 UTC, isyoudwn commented on src/main/java/com/tasksprints/auction/common/jwt/JwtProvider.java
> +        Date now = new Date(System.currentTimeMillis());
안녕하세요 태현님! 해당 사항 수정해서 PR 브랜치에 push 했습니다 :)
하지만, 수정하면서 아래의 이슈가 있었습니다! 같이 이야기 나누어보면 좋을 것 같습니다.

1. jjwt라이브러리는 Date만을 지원합니다.
다른 타입 지원은 아직 [개발 중](https://github.com/jwtk/jjwt/issues/235)이라고 합니다.

2. 따라서 TimeUtil 클래스를 만들어서 시간대를 localDateTime -> Date로 변환하는 방법으로 수정하였습니다.

4. 하지만 Date로 변환 과정에서 region이나 운영체제에 영향을 받을 수 있습니다.

- 그러나, 발급해주는 시간 자체를 한국으로 고정해서 발급했기 때문에 언제든 다시 한국 시간을 유추할 수 있어서 해당 방법을 사용했습니다. 
- 또한, jjwt 라이브러리에서 토큰을 검증할 때도 UTC 시간을 기준으로 비교 하기 때문에, 발급해주는 애플리케이션의 시간대만 고정되어있으면 괜찮을 것 같아서 먼저, 해당 방법을 선택해서 작업 했습니다.

2024-12-18 02:06 UTC, merged